name: exame-app
services:
  postgres:
    container_name: pg16
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=exame_db
    ports:
      - "5432:5432"
